---
# yamllint disable rule:line-length

name: main
on:  # yamllint disable-line rule:truthy
  push:
    branches: ["master", "other-*"]
    tags: ["*"]
  pull_request:
    branches: ["master", "other-*"]
  # Since this workflow must be able to be triggered manually so that it can be
  # started from another workflow
  workflow_dispatch:

jobs:
  the-job:
    name: TheJob
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28

      - name: See where we are
        run: |
          date
          git log --pretty="format:%h %G?%d %s" -1
          echo ""
          echo REF: ${{ github.ref }}
          echo REF_NAME: ${{ github.ref_name }}
          echo REF_TYPE: ${{ github.ref_type }}
          echo EVENT_NAME: ${{ github.event_name }}
          echo "File contents:"; cat thefile

      - name: See where we are
        run: |
          echo "I'm the b1 file"

      - name: Conditionals
        if: >
          (github.event_name == 'push' || github.event_name == 'schedule') &&
          (github.ref == 'refs/heads/master' ||
           startsWith(github.ref, 'refs/heads/other-') ||
           startsWith(github.ref, 'refs/tags/v'))
        run: echo "And I ran... I ran so far away... I just ran... I ran all night and day..."
