---
# yamllint disable rule:line-length

name: trigger
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  the-trigger-job:
    name: TheTriggerJob
    runs-on: ubuntu-20.04
    permissions:
      actions: write  # required to trigger a workflow

    steps:
      - name: Checkout source
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28

      - name: See where we are
        run: |
          date
          git log --pretty="format:%h %G?%d %s" -1
          echo ""
          echo REF: ${{ github.ref }}
          echo REF_NAME: ${{ github.ref_name }}
          echo REF_TYPE: ${{ github.ref_type }}
          echo EVENT_NAME: ${{ github.event_name }}
          echo "File contents:"; cat thefile

      - name: Trigger other workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run --ref master main
