---
# yamllint disable rule:line-length

name: Periodic
on:  # yamllint disable-line rule:truthy
  # Allow this workflow to be dispatched manually (for testing)
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * 1"  # 1:15 every Monday

jobs:
  trigger:
    name: Trigger other jobs
    runs-on: ubuntu-20.04

    steps:
      - env:
          # Must use a personal access token w/ workflow permissions. The GH
          # workflow token doesn't have permission to trigger other workflows
          # regardless of permissions granted.
          GITHUB_TOKEN: ${{ secrets.PAT_WORKFLOW }}
        run: |
          gh workflow run --ref "master" "main.yml"
          gh workflow run --ref "b1" "main2.yml"
          gh workflow run --ref "t1" "main.yml"
